Separated check on PR for non-staging branch to another job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,6 +8,19 @@ on:
   pull_request:
 
 jobs:
+  pr-target-test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if target is not staging (for PRs only)
+        if: github.event_name == 'pull_request'
+        run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" != "main" || "${{ github.event.pull_request.head.ref }}" == "staging" ]]; then
+            echo "Target branch is acceptable."
+          else
+            echo "Only PRs from staging can target main."
+            exit 1
+          fi
+          
   tests:
     runs-on: ubuntu-latest
     steps:
